### ISSUE TITLE
why need times 2

### ISSUE THREAD

**Issue by syahdeini** [emsansone/GAN#2]
Hi sorry to ask again. 
the optimum of desc is -log(2) right?  since it should be 1/2
why do you multiply it with 2?
https://github.com/emsansone/GAN/blob/5747f1e135deff2f7f49a93738c28e3dfd10f5b9/gan.py#L152

**Comment by emsansone** [comment]
Note that
-loss_discr = log(D_1)+log(1-D_2) = log(1/2)+log(1-1/2) = -log(2)-log(2) = -2log(2)
